# Generated by Django 4.2.7 on 2023-11-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_remove_product_description_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
