# Generated by Django 4.2.7 on 2023-11-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_bill_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
